source_path: "None"
model_path: "None"
train_json: "None"
test_json: "None"


time_num: 21 # Note that the default time_num is 21, which means the video has 21 frames. 
views_index: [0, 3, 6, 9, 12, 15, 18]  # SV3D generates 21 views, we only use 7 views here. 
time_indexs_that_use_novel_views: "0-21" # means that we use all novel views from the first frame to the last frame. 

downsample: 1.0
densify_until_iter: 10000
warm_up: 3000 
iterations: 25000 

white_background: True
eval: True
is_blender: True

# DPSR parameters
dpsr_iter: 12000
dpsr_sig: 3.0
grid_res: 288
gaussian_ratio: 1.2
init_density_threshold: 0.0

# Loss weights
mask_loss_weight: 1.0
mesh_img_loss_weight: 1.0
laplacian_loss_weight: 1.0

# Anchoring parameters
use_anchor: 1.0
anchor_iter: 16000
anchor_n_1_bs: 128
anchor_0_1_bs: 128
anchor_search_radius: 0.0015
anchor_interval: 100
